### ISSUE TITLE
Unable to delete currency

### ISSUE THREAD

**Issue by ray-equinox** [kabetani/CCMarket#2]
Thanks for taking the time to create this great app, and for posting it on GitHub! Nice learning example for creating a Fitbit Ionic app  :)

Am I missing something, or is it not possible to delete a currency (or clear settings)? I even tried uninstall, then re-installing, but settings were persisted.

**Comment by kabetani** [comment]
Thank you for your suggestion.
I added "Clear all settings" button on settings page.

Please try it.
Thanks.

**Comment by ray-equinox** [comment]
Awesome -- thank you! :)
